In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
!pip install mido
import numpy as np
import tensorflow as tf
#physical_devices = tf.config.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)
from tensorflow.keras.layers import Input, LSTM, Dropout, Dense, Flatten
from tensorflow.keras.models import Model

In [ ]:
import glob
import mido
from mido import MidiFile, MidiTrack, Message
notes = []
times = []
to_delete = []
count = 0
for folder in glob.glob('/content/drive/MyDrive/Major Project/datasets/maestro/*'):
  for midi in glob.glob(folder + '/*.midi'):
    #print(midi)
    print(count)
    try:
      mid = MidiFile(midi)
      for msg in mid:
        if not msg.is_meta and msg.type == 'note_on':
          notes.append(msg.note)
          times.append(msg.time)
              
    except:
      to_delete.append(midi)
      print("error " + str(count))

    count += 1

In [ ]:
np.save("/content/drive/MyDrive/Major Project/datasets/maestro_notes.npy", np.array(notes))
np.save("/content/drive/MyDrive/Major Project/datasets/maestro_times.npy", np.array(times))

In [ ]:
len(times)

14080328

In [3]:
pitchnames = sorted(set(item for item in notes))
print(pitchnames)
note_to_int = dict((note, number) for number, note in enumerate(pitchnames))
print(note_to_int)

[0, 22, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 98, 100, 105]
{0: 0, 22: 1, 24: 2, 26: 3, 27: 4, 28: 5, 29: 6, 30: 7, 31: 8, 32: 9, 33: 10, 34: 11, 35: 12, 36: 13, 37: 14, 38: 15, 39: 16, 40: 17, 41: 18, 42: 19, 43: 20, 44: 21, 45: 22, 46: 23, 47: 24, 48: 25, 49: 26, 50: 27, 51: 28, 52: 29, 53: 30, 54: 31, 55: 32, 56: 33, 57: 34, 58: 35, 59: 36, 60: 37, 61: 38, 62: 39, 63: 40, 64: 41, 65: 42, 66: 43, 67: 44, 68: 45, 69: 46, 70: 47, 71: 48, 72: 49, 73: 50, 74: 51, 75: 52, 76: 53, 77: 54, 78: 55, 79: 56, 80: 57, 81: 58, 82: 59, 83: 60, 84: 61, 85: 62, 86: 63, 87: 64, 88: 65, 89: 66, 90: 67, 92: 68, 93: 69, 94: 70, 95: 71, 98: 72, 100: 73, 105: 74}


In [46]:
import mido
from mido import MidiFile, MidiTrack, Message
import numpy as np

mid = MidiFile("/content/drive/MyDrive/Major Project/pnowks/corner.mid") 
notes = []
times = []

for msg in mid:
    if not msg.is_meta and msg.channel == 0 and msg.type == 'note_on' and msg.velocity != 0:
        data = msg.bytes()
        notes.append(data[1])
        times.append(msg.time)

print(notes)

[36, 48, 55, 60, 62, 64, 55, 60, 64, 62, 53, 60, 62, 65, 57, 59, 65, 64, 55, 60, 64, 67, 59, 60, 67, 65, 57, 60, 65, 69, 59, 65, 69, 67, 60, 64, 67, 72, 60, 64, 67, 72, 59, 74, 64, 67, 74, 72, 57, 64, 67, 72, 59, 71, 64, 67, 71, 60, 69, 64, 67, 69, 67, 59, 60, 64, 67, 57, 65, 60, 64, 65, 64, 55, 59, 60, 64, 62, 53, 57, 60, 62, 67, 52, 59, 64, 67, 69, 57, 60, 64, 69, 55, 64, 57, 60, 64, 62, 53, 57, 60, 62, 60, 52, 55, 57, 60, 50, 59, 53, 55, 59, 41, 48, 50, 52, 53, 57, 60, 62, 64, 62, 60, 57, 53, 52, 50, 48, 41, 48, 50, 52, 53, 57, 60, 62, 64, 62, 60, 59, 57, 52, 50, 48, 41, 48, 50, 52, 53, 56, 60, 62, 64, 62, 60, 56, 53, 52, 50, 48, 41, 48, 50, 52, 53, 56, 60, 62, 64, 62, 60, 58, 56, 52, 50, 48, 40, 47, 52, 56, 47, 52, 56, 59, 52, 56, 59, 64, 56, 59, 64, 68, 64, 69, 65, 62, 64, 65, 62, 59, 64, 69, 65, 62, 64, 65, 62, 59, 67, 72, 69, 65, 64, 69, 65, 62, 60, 65, 62, 59, 57, 62, 59, 55, 64, 69, 65, 62, 64, 65, 62, 59, 64, 69, 65, 62, 64, 65, 62, 59, 67, 72, 69, 65, 64, 69, 65, 62, 60, 65,

In [48]:
from sklearn.preprocessing import MinMaxScaler

def scaling(data, feature_range = (0, 1)):
  scaler = MinMaxScaler(feature_range)
  scaler.fit(np.array(data).reshape(-1, 1))
  transformed_data = list(scaler.transform(np.array(data).reshape(-1, 1)))
  return transformed_data, scaler

In [49]:
scaled_notes, notes_scaler = scaling(notes)
scaled_times = [max(0, -np.log10(time + 0.0001)) for time in times]
scaled_times = np.array(scaled_times).reshape(-1, 1)

In [47]:
len(notes)

6052

In [50]:
notes_with_times = []
i = 0
for note in list(scaled_notes):
    temp = []
    temp.append(note)
    temp.append(scaled_times[i])
    notes_with_times.append(temp)
    i += 1
notes_with_times = np.array(notes_with_times).reshape(-1, 2)
notes_with_times.shape

(6052, 2)

In [51]:
notes_with_times

array([[0.34285714, 0.87473566],
       [0.45714286, 0.59471057],
       [0.52380952, 0.2902214 ],
       ...,
       [0.48571429, 0.        ],
       [0.37142857, 2.36991129],
       [0.25714286, 2.36991129]])

In [52]:
notes_with_times = [list(note) for note in notes_with_times]

X = []

# number of notes in a sequence
n_prev = 100
for i in range(0, len(notes_with_times)-n_prev, 10):
  X.append(notes_with_times[i : i + n_prev])
  
#for i in range(0, len(notes_with_times) - n_prev, n_prev):
  #X.append(notes_with_times[i : i + n_prev])

X = np.array(X)
print(X[1, 0:10])
print(X.shape)

[[0.5047619  1.89962945]
 [0.57142857 1.37917018]
 [0.59047619 2.07400073]
 [0.61904762 4.        ]
 [0.54285714 1.89962945]
 [0.56190476 0.82361931]
 [0.61904762 4.        ]
 [0.60952381 4.        ]
 [0.52380952 4.        ]
 [0.57142857 1.53362674]]
(596, 100, 2)


In [53]:
def generator():
    gen_input = Input(shape = (None, 100))
    X = LSTM(256, return_sequences = True)(gen_input)
    X = Dropout(0.5)(X)
    X = LSTM(128, return_sequences = True)(X)
    X = Dropout(0.5)(X)
    X = LSTM(64, return_sequences = True)(X)
    X = Dropout(0.5)(X)
    out = Dense(2, activation = "relu")(X)
    model = Model(inputs = gen_input, outputs = out)
    return model

In [54]:
def discriminator():
    disc_input = Input(shape = (100, 2))
    X = LSTM(128, return_sequences = True)(disc_input)
    X = Dropout(0.3)(X)
    X = LSTM(64, return_sequences = True)(X)
    X = Dropout(0.3)(X)
    X = Flatten()(X)
    X = Dense(128, activation = "relu")(X)
    X = Dropout(0.3)(X)
    out = Dense(1, activation = "sigmoid")(X)
    model = Model(inputs = disc_input, outputs = out)
    return model

In [55]:
def disc_with_gen(generator, discriminator):
    inputs = Input(shape = (None, 100))
    generated = generator(inputs)
    outputs = discriminator(generated)
    model = Model(inputs = inputs, outputs = outputs)
    return model

In [56]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(0.0002, 0.5)
d = discriminator()
d.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
g = generator()

In [57]:
d.trainable = False
combined = disc_with_gen(g, d)
combined.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [58]:
X.shape

(596, 100, 2)

In [59]:
from matplotlib import pyplot as plt
assert not np.any(np.isnan(X))

In [60]:
disc_loss = []
disc_loss_epoch = []
gen_loss = []
gen_loss_epoch = []
batch_size = 64

In [61]:
idx = list(range(0, batch_size, 1))
real_data = X[idx]
real_data.shape

(64, 100, 2)

In [62]:
def train(epochs, num_of_batches, batch_size = batch_size):
    for epoch in range(epochs):
        a = 0
        b = batch_size
        for num in range(num_of_batches):
            idx = list(range(a, b, 1))
            real_data = X[idx]

            noise = np.random.normal(0, 1, (batch_size, 100, 100))

            generated = g.predict(noise)
            d_loss_real = d.train_on_batch(real_data, np.ones((batch_size, 1)))
            #print("d_loss_real: ", d_loss_real)
            d_loss_fake = d.train_on_batch(generated, np.zeros((batch_size, 1)))
            #print("d_loss_fake: ",d_loss_fake)
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)
            print("d_loss: ",d_loss)
            
            noise = np.random.normal(0, 1, (batch_size, 100, 100))
            g_loss = combined.train_on_batch(noise, np.ones((batch_size, 1)))
            print("g_loss: ", g_loss)

            disc_loss.append(d_loss[0])
            gen_loss.append(g_loss[0])

            a = a + batch_size
            b = b + batch_size
            
        if epoch % 1 == 0:
            print ("%d [D loss: %f, acc.: %.2f%%] [G loss: %f, acc.: %.2f%%]" % (epoch, d_loss[0], 100*d_loss[1], g_loss[0], 100*g_loss[1]))
            disc_loss_epoch.append(d_loss[0])
            gen_loss_epoch.append(g_loss[0])
            
    plt.plot(disc_loss, c='red')
    plt.plot(gen_loss, c='blue')
    plt.title("GAN Loss per batch")
    plt.legend(['Discriminator', 'Generator'])
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.savefig('/content/drive/MyDrive/Major Project/output/GAN_Loss_per_Batch_final.png', transparent=False)
    plt.close()

    plt.plot(disc_loss_epoch, c='red')
    plt.plot(gen_loss_epoch, c='blue')
    plt.title("GAN Loss per Epoch")
    plt.legend(['Discriminator', 'Generator'])
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.savefig('/content/drive/MyDrive/Major Project/output/GAN_Loss_per_Epoch_final.png', transparent=False)
    plt.close()

In [63]:
print(real_data.shape)
generated = g.predict(np.random.normal(0, 1, (batch_size, 100, 100)))
print(generated.shape)
idx = list(range(0, batch_size, 1))
print(real_data[idx])

(64, 100, 2)
(64, 100, 2)
[[[0.34285714 0.87473566]
  [0.45714286 0.59471057]
  [0.52380952 0.2902214 ]
  ...
  [0.59047619 1.33787204]
  [0.5047619  2.36991129]
  [0.54285714 1.67916161]]

 [[0.5047619  1.89962945]
  [0.57142857 1.37917018]
  [0.59047619 2.07400073]
  ...
  [0.47619048 1.77555327]
  [0.56190476 2.36991129]
  [0.5047619  2.36991129]]

 [[0.60952381 1.03731504]
  [0.63809524 0.98185451]
  [0.56190476 1.37917018]
  ...
  [0.54285714 4.        ]
  [0.57142857 1.89962945]
  [0.59047619 1.03731504]]

 ...

 [[0.58095238 1.89962945]
  [0.51428571 1.12436006]
  [0.55238095 0.5539809 ]
  ...
  [0.65714286 1.17544031]
  [0.54285714 1.67916161]
  [0.57142857 0.98185451]]

 [[0.2952381  1.89962945]
  [0.52380952 0.51083869]
  [0.57142857 1.67916161]
  ...
  [0.59047619 1.77555327]
  [0.5047619  1.77555327]
  [0.54285714 1.30016227]]

 [[0.57142857 0.94846161]
  [0.59047619 1.1009094 ]
  [0.61904762 0.98185451]
  ...
  [0.47619048 1.05749589]
  [0.56190476 2.07400073]
  [0.5047619

In [64]:
train(epochs = 20, num_of_batches = int(X.shape[0]/batch_size))

d_loss:  [0.68791857 0.328125  ]
g_loss:  [0.6795495748519897, 1.0]
d_loss:  [0.53014839 0.5       ]
g_loss:  [0.664710521697998, 1.0]
d_loss:  [0.45105325 0.5       ]
g_loss:  [0.6416856050491333, 1.0]
d_loss:  [0.40906702 0.515625  ]
g_loss:  [0.6219114065170288, 0.984375]
d_loss:  [0.43380447 0.5       ]
g_loss:  [0.595855176448822, 0.984375]
d_loss:  [0.4575232 0.5      ]
g_loss:  [0.6096822023391724, 0.953125]
d_loss:  [0.48107193 0.5078125 ]
g_loss:  [0.6268966197967529, 0.90625]
d_loss:  [0.51318258 0.5       ]
g_loss:  [0.7382017374038696, 0.203125]
d_loss:  [0.56015444 0.515625  ]
g_loss:  [0.8063925504684448, 0.046875]
0 [D loss: 0.560154, acc.: 51.56%] [G loss: 0.806393, acc.: 4.69%]
d_loss:  [0.71100035 0.4921875 ]
g_loss:  [0.8710836172103882, 0.046875]
d_loss:  [0.55327678 0.7578125 ]
g_loss:  [1.0914795398712158, 0.015625]
d_loss:  [0.49503219 0.9453125 ]
g_loss:  [1.0743716955184937, 0.0]
d_loss:  [0.40557183 0.8984375 ]
g_loss:  [1.0995680093765259, 0.015625]
d_loss:  

In [ ]:
g.save_weights("/content/drive/MyDrive/Major Project/saved_weights/Model_weights_1.h5")

In [ ]:
g.load_weights("/content/drive/MyDrive/Major Project/saved_weights/Model_weights.h5")

In [ ]:
g.save("/content/drive/MyDrive/Major Project/saved_models/Model_1.h5")

In [ ]:
g = tf.keras.models.load_model("/content/drive/MyDrive/Major Project/saved_models/Model/Model2.h5")

In [ ]:
d.metrics_names[1]

'accuracy'

In [34]:
pred = g.predict(np.random.normal(0, 1, (1, 100, 100)))
d.predict(pred)

array([[0.42408997]], dtype=float32)

In [35]:
d.predict(X[100, :, :].reshape(1, 100, 2))

array([[0.44851595]], dtype=float32)

In [33]:
prediction = g.predict(np.random.normal(0, 1, (1, 100, 100)))
print(prediction)

[[[0.31840587 0.9400756 ]
  [0.7759445  2.289402  ]
  [0.91204125 2.737812  ]
  [0.69956565 2.0046144 ]
  [0.4548013  1.1136535 ]
  [0.39360547 0.7901329 ]
  [0.41951928 0.79076123]
  [0.48029536 0.87515223]
  [0.6240446  1.1585784 ]
  [0.9714251  2.1651585 ]
  [1.1814188  3.0631442 ]
  [0.98905325 2.5707982 ]
  [0.5783171  1.328074  ]
  [0.40719005 0.8237753 ]
  [0.4299513  0.87316835]
  [0.4955806  1.0638192 ]
  [0.6370458  1.4185941 ]
  [0.77617496 1.8224503 ]
  [0.83202523 2.0221143 ]
  [0.7178569  1.7284216 ]
  [0.58955216 1.3726611 ]
  [0.51223135 1.1651514 ]
  [0.5459138  1.2240196 ]
  [0.62578714 1.4378288 ]
  [0.84168655 2.0278246 ]
  [0.9487618  2.3742604 ]
  [0.8771456  2.0820837 ]
  [0.56468374 1.1609637 ]
  [0.4064632  0.7050616 ]
  [0.40464893 0.73892653]
  [0.46705705 0.95176893]
  [0.57975954 1.273957  ]
  [0.7967623  1.8649981 ]
  [0.99761176 2.4580948 ]
  [0.86127204 2.0743954 ]
  [0.5340369  1.1438026 ]
  [0.3958065  0.72394925]
  [0.41825214 0.78046334]
  [0.4745617

In [36]:
predicted_notes = []
predicted_times = []
for p in prediction.reshape(-1, 2):
    predicted_notes.append(p[0])
    predicted_times.append(p[1])
print(np.array(predicted_notes).shape)
print(np.array(predicted_times).shape)
print(predicted_notes)
print(predicted_times)

(100,)
(100,)
[0.31840587, 0.7759445, 0.91204125, 0.69956565, 0.4548013, 0.39360547, 0.41951928, 0.48029536, 0.6240446, 0.9714251, 1.1814188, 0.98905325, 0.5783171, 0.40719005, 0.4299513, 0.4955806, 0.6370458, 0.77617496, 0.83202523, 0.7178569, 0.58955216, 0.51223135, 0.5459138, 0.62578714, 0.84168655, 0.9487618, 0.8771456, 0.56468374, 0.4064632, 0.40464893, 0.46705705, 0.57975954, 0.7967623, 0.99761176, 0.86127204, 0.5340369, 0.3958065, 0.41825214, 0.47456175, 0.580624, 0.80763596, 1.1046088, 1.061566, 0.6583958, 0.38299447, 0.3700945, 0.42918563, 0.49560076, 0.7245445, 1.0253086, 1.0483987, 0.6616548, 0.38911414, 0.38296896, 0.44644055, 0.5633046, 0.8358291, 1.1291488, 0.9913722, 0.5448784, 0.37470198, 0.41197208, 0.4645911, 0.62145466, 0.95650715, 1.0786461, 0.71250993, 0.3981181, 0.40189984, 0.45781657, 0.53078765, 0.7689562, 1.126653, 1.1110853, 0.63369334, 0.36283118, 0.38096693, 0.44113487, 0.5309518, 0.8333632, 1.1521949, 1.0376688, 0.5821031, 0.36925602, 0.37554795, 0.43128052

In [37]:
_notes = notes_scaler.inverse_transform(np.array(predicted_notes).reshape(-1,1))
final_notes = [int(i) for i in _notes]
final_notes

[33,
 81,
 95,
 73,
 47,
 41,
 44,
 50,
 65,
 101,
 124,
 103,
 60,
 42,
 45,
 52,
 66,
 81,
 87,
 75,
 61,
 53,
 57,
 65,
 88,
 99,
 92,
 59,
 42,
 42,
 49,
 60,
 83,
 104,
 90,
 56,
 41,
 43,
 49,
 60,
 84,
 115,
 111,
 69,
 40,
 38,
 45,
 52,
 76,
 107,
 110,
 69,
 40,
 40,
 46,
 59,
 87,
 118,
 104,
 57,
 39,
 43,
 48,
 65,
 100,
 113,
 74,
 41,
 42,
 48,
 55,
 80,
 118,
 116,
 66,
 38,
 40,
 46,
 55,
 87,
 120,
 108,
 61,
 38,
 39,
 45,
 52,
 79,
 113,
 113,
 74,
 42,
 39,
 45,
 51,
 71,
 107,
 117,
 81,
 42]

In [38]:
final_times = [10**(-time) for time in predicted_times]
final_times

[0.11479538361838963,
 0.00513568043247372,
 0.0018288915685724125,
 0.009894313044608007,
 0.07697442606114704,
 0.1621313951285151,
 0.16189698747567893,
 0.1333054083964995,
 0.06940992963887112,
 0.006836620765382792,
 0.0008646807548170876,
 0.0026865927680623978,
 0.046981407290008416,
 0.1500460989071516,
 0.13391574777896922,
 0.08633379465428297,
 0.03814221220848741,
 0.015050458127468472,
 0.00950354691780503,
 0.01868867153629705,
 0.04239736697884362,
 0.06836733361160478,
 0.05970082784700755,
 0.03648977796714979,
 0.0093794065280059,
 0.004224152361500469,
 0.008277826088193174,
 0.06902975714359737,
 0.19721429231038948,
 0.18242042790321042,
 0.11174576301335445,
 0.05321609292729254,
 0.013645890996574582,
 0.003482612582079985,
 0.008425672644282149,
 0.07181205538745453,
 0.1888211969995566,
 0.16578172799128263,
 0.11003158700227819,
 0.05725467453770384,
 0.014005697001198249,
 0.0017415398572918777,
 0.0022278030140894145,
 0.03766395707763639,
 0.22025149899664

In [66]:
from mido import MidiFile, MidiTrack, Message
mid = MidiFile()
track = MidiTrack()
for i in range(500):
    # 147 means note_on
    # 67 is velocity
    note = np.asarray([147, notes[i], 67])
    bytes = note.astype(int)
    msg = Message.from_bytes(bytes[0:3])
    time = times[i]
    msg.time = round(time * mid.ticks_per_beat * 2)
    if msg.note > 21 or msg.note < 109:
      track.append(msg)
mid.tracks.append(track)
mid.save('/content/drive/MyDrive/Major Project/output/GAN_music.mid')
for msg in mid:
  print(msg)

note_on channel=3 note=36 velocity=67 time=0.13333333333333333
note_on channel=3 note=48 velocity=67 time=0.25416666666666665
note_on channel=3 note=55 velocity=67 time=0.5125
note_on channel=3 note=60 velocity=67 time=0.12083333333333333
note_on channel=3 note=62 velocity=67 time=0.016666666666666666
note_on channel=3 note=64 velocity=67 time=0.025
note_on channel=3 note=55 velocity=67 time=0.05416666666666667
note_on channel=3 note=60 velocity=67 time=0.125
note_on channel=3 note=64 velocity=67 time=0.020833333333333332
note_on channel=3 note=62 velocity=67 time=0.025
note_on channel=3 note=53 velocity=67 time=0.0125
note_on channel=3 note=60 velocity=67 time=0.041666666666666664
note_on channel=3 note=62 velocity=67 time=0.008333333333333333
note_on channel=3 note=65 velocity=67 time=0
note_on channel=3 note=57 velocity=67 time=0.0125
note_on channel=3 note=59 velocity=67 time=0.15
note_on channel=3 note=65 velocity=67 time=0
note_on channel=3 note=64 velocity=67 time=0
note_on chan

In [109]:
from mido import MidiFile, MidiTrack, Message
mid = MidiFile()
track = MidiTrack()
t = 230
track.append(Message('program_change', program = 0, channel = 0, time = 0))
for note in final_notes:
    # 147 means note_on
    # 67 is velocity
    note = np.asarray([147, note, 67])
    bytes = note.astype(int)
    msg = Message.from_bytes(bytes[0:3])
    if t >= 180:
        t -= 2
    msg.time = int(t)
    msg.channel = 0
    track.append(msg)
mid.tracks.append(track)
mid.save('/content/drive/MyDrive/Major Project/output/LSTM_music.mid')
for msg in mid:
  print(msg)

program_change channel=0 program=0 time=0
note_on channel=0 note=44 velocity=67 time=0.2375
note_on channel=0 note=80 velocity=67 time=0.23541666666666666
note_on channel=0 note=101 velocity=67 time=0.23333333333333334
note_on channel=0 note=90 velocity=67 time=0.23124999999999998
note_on channel=0 note=55 velocity=67 time=0.22916666666666666
note_on channel=0 note=31 velocity=67 time=0.22708333333333333
note_on channel=0 note=26 velocity=67 time=0.225
note_on channel=0 note=49 velocity=67 time=0.22291666666666665
note_on channel=0 note=89 velocity=67 time=0.22083333333333333
note_on channel=0 note=107 velocity=67 time=0.21875
note_on channel=0 note=93 velocity=67 time=0.21666666666666667
note_on channel=0 note=62 velocity=67 time=0.21458333333333332
note_on channel=0 note=32 velocity=67 time=0.2125
note_on channel=0 note=23 velocity=67 time=0.21041666666666667
note_on channel=0 note=46 velocity=67 time=0.20833333333333334
note_on channel=0 note=89 velocity=67 time=0.20625
note_on chan

In [45]:
import mido
from mido import MidiFile, MidiTrack, Message
import numpy as np

#mid = MidiFile('/content/drive/MyDrive/Major Project/datasets/maestro/maestro-v3.0.0-2004/MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_05_Track05_wav.midi')
mid = MidiFile('/content/drive/MyDrive/Major Project/datasets/midi_songs/EyesOnMePiano.mid') 

for msg in mid:
  print(msg)

<meta message text text='By NoteWorthy Composer' time=0>
<meta message copyright text='Copyright © 2006 NoteWorthy Software, Inc.' time=0>
<meta message copyright text='All Rights Reserved' time=0>
<meta message text text='Generated by NoteWorthy Composer' time=0>
<meta message set_tempo tempo=631578 time=0>
<meta message key_signature key='D' time=0>
<meta message time_signature numerator=4 denominator=4 clocks_per_click=24 notated_32nd_notes_per_beat=8 time=0>
<meta message midi_port port=0 time=0>
<meta message track_name name='Staff' time=0>
program_change channel=0 program=0 time=0
control_change channel=0 control=7 value=127 time=0
control_change channel=0 control=10 value=64 time=0
control_change channel=0 control=64 value=127 time=0
note_on channel=0 note=81 velocity=45 time=0
<meta message midi_port port=0 time=0>
<meta message track_name name='Staff-1' time=0>
program_change channel=1 program=0 time=0
control_change channel=1 control=7 value=127 time=0
control_change channel=

In [ ]:
b = [1,2,3,4,5,6,7,8,9]
a = list(np.array(b).reshape(-1,1))
note = [list(v) for v in a]
print(a)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9])]


In [ ]:
import mido
from mido import MidiFile, MidiTrack, Message
import numpy as np

#mid = MidiFile('/content/drive/MyDrive/Major Project/output/LSTM_music.mid')
mid = MidiFile('corner.mid')
midy = MidiFile()
track = MidiTrack()

start = 0

midy.ticks_per_beat = mid.ticks_per_beat

for msg in mid:
    msg.time = round(msg.time * midy.ticks_per_beat * 2)
    if not msg.is_meta and msg.channel == 0 and msg.type == 'note_on':
        msg.note = prediction[start]
        start += 1
        track.append(msg)
        if start >= len(prediction):
            break
    else:
        track.append(msg)
midy.tracks.append(track)
midy.save("/content/drive/MyDrive/Major Project/output/lstmaa.mid")

In [ ]:
for msg in mid:
    print(msg)

<meta message track_name name='untitled' time=0>
<meta message time_signature numerator=4 denominator=4 clocks_per_click=24 notated_32nd_notes_per_beat=8 time=0>
<meta message key_signature key='C' time=0>
<meta message set_tempo tempo=500000 time=0>
<meta message midi_port port=0 time=0>
<meta message track_name name='Piano' time=0>
control_change channel=0 control=0 value=0 time=0
control_change channel=0 control=32 value=0 time=0
program_change channel=0 program=0 time=0
control_change channel=0 control=64 value=127 time=2.0708333333333333
control_change channel=0 control=64 value=0 time=0.10833333333333334
control_change channel=0 control=64 value=127 time=0.2833333333333333
control_change channel=0 control=67 value=127 time=0.0375
note_on channel=0 note=36 velocity=54 time=0.13333333333333333
note_on channel=0 note=48 velocity=73 time=0.25416666666666665
note_on channel=0 note=55 velocity=52 time=0.5125
note_on channel=0 note=60 velocity=60 time=0.12083333333333333
note_on channel

note_on channel=0 note=54 velocity=0 time=0.008333333333333333
note_on channel=0 note=63 velocity=0 time=0.020833333333333332
note_on channel=0 note=46 velocity=0 time=0.09166666666666666
note_on channel=0 note=63 velocity=73 time=0.03333333333333333
note_on channel=0 note=54 velocity=62 time=0.0125
note_on channel=0 note=58 velocity=62 time=0.008333333333333333
note_on channel=0 note=54 velocity=0 time=0.025
note_on channel=0 note=58 velocity=0 time=0.016666666666666666
note_on channel=0 note=63 velocity=0 time=0.020833333333333332
control_change channel=0 control=64 value=0 time=0.17916666666666667
note_on channel=0 note=44 velocity=64 time=0.0125
note_on channel=0 note=61 velocity=82 time=0.004166666666666667
note_on channel=0 note=56 velocity=70 time=0.004166666666666667
note_on channel=0 note=53 velocity=69 time=0.016666666666666666
control_change channel=0 control=64 value=127 time=0
note_on channel=0 note=53 velocity=0 time=0.075
note_on channel=0 note=56 velocity=0 time=0.00416

note_on channel=0 note=80 velocity=103 time=0.0375
note_on channel=0 note=66 velocity=76 time=0.0125
note_on channel=0 note=64 velocity=72 time=0.008333333333333333
note_on channel=0 note=64 velocity=0 time=0.16666666666666666
note_on channel=0 note=66 velocity=0 time=0.0125
note_on channel=0 note=73 velocity=0 time=0.09583333333333333
note_on channel=0 note=80 velocity=0 time=0.0125
note_on channel=0 note=70 velocity=0 time=0
note_on channel=0 note=61 velocity=83 time=0.07083333333333333
note_on channel=0 note=61 velocity=0 time=0.03333333333333333
note_on channel=0 note=54 velocity=54 time=0.32916666666666666
note_on channel=0 note=54 velocity=0 time=0.08333333333333333
note_on channel=0 note=64 velocity=53 time=0.25416666666666665
note_on channel=0 note=67 velocity=57 time=0.016666666666666666
note_on channel=0 note=70 velocity=62 time=0.1875
note_on channel=0 note=64 velocity=0 time=0.125
note_on channel=0 note=58 velocity=60 time=0
note_on channel=0 note=60 velocity=49 time=0.0125

note_on channel=0 note=63 velocity=0 time=0.10416666666666667
note_on channel=0 note=58 velocity=82 time=0.029166666666666667
note_on channel=0 note=61 velocity=83 time=0
control_change channel=0 control=64 value=0 time=0
note_on channel=0 note=70 velocity=77 time=0.016666666666666666
note_on channel=0 note=73 velocity=82 time=0.004166666666666667
control_change channel=0 control=64 value=127 time=0.075
note_on channel=0 note=70 velocity=0 time=0.041666666666666664
note_on channel=0 note=73 velocity=0 time=0.05
note_on channel=0 note=65 velocity=76 time=0.0125
note_on channel=0 note=58 velocity=0 time=0.0125
note_on channel=0 note=61 velocity=0 time=0.0125
note_on channel=0 note=65 velocity=0 time=0.0375
note_on channel=0 note=63 velocity=83 time=0.06666666666666667
note_on channel=0 note=63 velocity=0 time=0.058333333333333334
note_on channel=0 note=63 velocity=83 time=0.04583333333333333
note_on channel=0 note=63 velocity=0 time=0.06666666666666667
note_on channel=0 note=63 velocity=

note_on channel=0 note=57 velocity=0 time=0.0125
note_on channel=0 note=42 velocity=0 time=0.008333333333333333
control_change channel=0 control=67 value=104 time=0.11666666666666667
control_change channel=0 control=67 value=88 time=0.008333333333333333
control_change channel=0 control=67 value=72 time=0.008333333333333333
control_change channel=0 control=67 value=56 time=0.0125
control_change channel=0 control=67 value=40 time=0
control_change channel=0 control=67 value=24 time=0.020833333333333332
control_change channel=0 control=67 value=0 time=0.004166666666666667
note_on channel=0 note=49 velocity=59 time=0.0875
note_on channel=0 note=57 velocity=54 time=0.3125
note_on channel=0 note=58 velocity=67 time=0.0625
note_on channel=0 note=61 velocity=66 time=0.004166666666666667
note_on channel=0 note=42 velocity=63 time=0.020833333333333332
note_on channel=0 note=61 velocity=0 time=0.0125
note_on channel=0 note=58 velocity=0 time=0.016666666666666666
note_on channel=0 note=57 velocity=

In [ ]:
for msg in midy:
    print(msg)

<meta message track_name name='untitled' time=0>
<meta message time_signature numerator=4 denominator=4 clocks_per_click=24 notated_32nd_notes_per_beat=8 time=0>
<meta message key_signature key='C' time=0>
<meta message set_tempo tempo=500000 time=0>
<meta message midi_port port=0 time=0>
<meta message track_name name='Piano' time=0>
control_change channel=0 control=0 value=0 time=0
control_change channel=0 control=32 value=0 time=0
program_change channel=0 program=0 time=0
control_change channel=0 control=64 value=127 time=2.0708333333333333
control_change channel=0 control=64 value=0 time=0.10833333333333334
control_change channel=0 control=64 value=127 time=0.2833333333333333
control_change channel=0 control=67 value=127 time=0.0375
note_on channel=0 note=69 velocity=54 time=0.13333333333333333
note_on channel=0 note=46 velocity=73 time=0.25416666666666665
note_on channel=0 note=89 velocity=52 time=0.5125
note_on channel=0 note=57 velocity=60 time=0.12083333333333333
note_on channel

In [ ]:
midy.ticks_per_beat

120

In [ ]:
int(X.shape[0]/batch_size)

407