In [1]:
import keras
from keras.layers import Lambda,Input,InputLayer, Dense, Activation, Dropout, Flatten, Reshape,ActivityRegularization, TimeDistributed
from keras.layers.embeddings import Embedding
from keras.layers.normalization import BatchNormalization
from keras.losses import binary_crossentropy
from keras.models import Model, Sequential, load_model
from keras.optimizers import Adam, RMSprop, SGD
from keras.regularizers import l2
from keras.utils import plot_model
from keras import backend as K
from keras.callbacks import ModelCheckpoint
from keras import regularizers

Using TensorFlow backend.


In [12]:
import numpy as np
import pandas as pd

In [13]:
x_vecs=np.load('input (1).npy')

In [14]:
latent_dim=100
latent_inputs=Input(shape=(latent_dim,),name='z_sampling')
x=Dense(16*96*35,name='decoder_1st_layer')(latent_inputs)
x=Activation('sigmoid')(x)
outputs=Reshape((16,96,35))(x)

In [8]:
latent_dim=100
num_epoch=1000
learning_rate=0.001
is_AE=False
is_VAE=True
dropout_rate=0.1
epsilon_std=1
batch_size=1024
num_measures=16
latent_dim=100
NUM_OFFSETS=16
MAX_LENGTH=16
BN_M=0.9
DO_RATE=dropout_rate

latent_inputs=Input(shape=(latent_dim,),name='z_sampling')
x=Dense(1600, name='decoder_1st_layer')(latent_inputs)
x=Activation('relu')(x)
x=BatchNormalization(momentum=BN_M)(x)
x=Dropout(DO_RATE)(x)
x=Dense(MAX_LENGTH * 200)(x)
x=Reshape((MAX_LENGTH, 200))(x)
x=Activation('relu')(x)
x=TimeDistributed(BatchNormalization(momentum=BN_M))(x)
x=Dropout(DO_RATE)(x)
x=TimeDistributed(Dense(2000))(x)  
x=Activation('relu')(x)
x=TimeDistributed(BatchNormalization(momentum=BN_M))(x)
x=Dropout(DO_RATE)(x)
x=TimeDistributed(Dense(96* 35, activation='sigmoid'))(x)
outputs=Reshape((16, 96, 35))(x)


In [9]:
decoder=Model(latent_inputs,outputs)


In [10]:
decoder.get_weights()

[array([[ 0.00680287, -0.03921757, -0.00371298, ..., -0.05226652,
          0.00498132,  0.0020843 ],
        [ 0.00417534,  0.02108145, -0.01639921, ...,  0.00707051,
         -0.020446  , -0.00662569],
        [-0.04323403, -0.01310662,  0.00885502, ..., -0.03502665,
          0.05613561, -0.0421523 ],
        ...,
        [ 0.02572788,  0.02941308, -0.05194991, ...,  0.03180371,
          0.01372943, -0.02454841],
        [ 0.05286638,  0.05586917,  0.02133989, ...,  0.00963674,
         -0.00442316,  0.03694326],
        [ 0.0091102 ,  0.05284269,  0.04022998, ..., -0.04558751,
          0.00915588,  0.02783882]], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([1., 1., 1., ..., 1., 1., 1.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([1., 1., 1., ..., 1., 1., 1.], dtype=float32),
 array([[-3.25502083e-02, -1.54896677e-02, -3.43513861e-03, ...,
         -1.89352557e-0

In [11]:
decoder.load_weights('decoder_weights.h5')
decoder.save('dec.h5')

In [9]:
decoder.get_weights()

[array([[ 0.00470167,  0.01311897,  0.02193928, ...,  0.00700491,
          0.00230018,  0.001513  ],
        [-0.09283218, -0.08589464, -0.09994651, ..., -0.08769749,
         -0.08832498, -0.10148872],
        [ 0.06991839,  0.08563377,  0.08870849, ...,  0.07776058,
          0.08909364,  0.0868546 ],
        ...,
        [-0.08928997, -0.09182365, -0.08274685, ..., -0.09559567,
         -0.0815106 , -0.0826944 ],
        [-0.01463328, -0.0139947 , -0.01022033, ..., -0.01532504,
         -0.01919311, -0.02011459],
        [ 0.08880052,  0.0909861 ,  0.09500765, ...,  0.08233221,
          0.1006769 ,  0.08334906]], dtype=float32),
 array([-0.13572277, -0.13647918, -0.13656248, ..., -0.13585208,
        -0.1355859 , -0.1356593 ], dtype=float32)]

In [ ]:
decoder.get_weights()

In [ ]:
decoder=load_model("dec.h5")
decoder.get_weights()

In [ ]:
model=decoder
for i in range(10):
        song=model.predict(x_vecs[i:i+1])[0]
        print(song.shape)
        data[:,:,30:65]=song
        samples_to_midi(data,str(i)+'.mid',16,0.1)

In [10]:
import random

In [24]:
random.randrange(10)

0

In [25]:
from tensorflow import Graph

In [26]:
tensorflow.__version__

NameError: name 'tensorflow' is not defined

In [1]:
import numpy as np

In [2]:
np.load('index.npy')

array([15, 81, 72, 67, 45, 52, 78, 44,  0, 39, 31, 18, 28, 85, 26, 80, 41,
       95, 86, 71, 61, 40, 62, 75, 30, 54, 37, 20, 38, 16, 19, 11, 55, 73,
       48, 60, 21, 33, 77, 58, 89, 12, 43, 49, 36, 88, 29, 42, 82, 92, 13,
       46,  2, 50, 66, 64, 47, 98,  8, 69, 10, 65, 96, 23,  6, 63, 53, 83,
       84, 94, 25, 14,  1, 34,  4, 76, 22, 32, 91, 51, 74, 79, 57, 56, 70,
        3, 35,  9, 93, 68, 87, 27, 97,  5, 24, 59,  7, 17, 90, 99])